apiVersion: v1
kind: Service
metadata:
  name: h2o-service
  namespace: h2o
spec:
  selector:
    app: h2o-k8s
  type: ClusterIP
  clusterIP: None
  ports:
  - protocol: TCP
    port: 80
    targetPort: 54321