apiVersion: v1
kind: StatefulSet
metadata:
  name: h2o-stateful-set
  namespace: h2o
spec:
  serviceName: h2o-service
  replicas: 3
  selector:
    matchLabels:
      app: h2o-k8s
  template:
    metadata:
    labels:
      app: h2o-k8s
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: h2o-k8s
          image:
          resources:
            requests:
              memory: "4Gi"
          ports:
            - containerPort: 54321
