apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-manager-binding
  namespace: spark
subjects:
- kind: User
  name: spark
  apiGroup: ""
roleRef:
  kind: Role 
  name: spark-manager
  apiGroup: ""