apiVersion : apps/v1
kind: Deployment
metadata:
  name: matcher-deployment
  namespace: postgres
  labels:
    app: matcher-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: matcher-pod
  template:
    metadata:
      labels:
        app: matcher-pod
    spec:
      containers:
      - name: matcher-pod
        image: 19911995/matcher:v1
        ports:
        - containerPort: 3000
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: superUserPassword
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: matcher-configmap
                key: postgresUser
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: matcher-configmap
                key: postgresHost
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: matcher-configmap
                key: postgresDatabase