apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-manager-binding
  namespace: nginx-ingress
subjects:
  kind: ServiceAccount
  name: nginx-ingress-sa
  namespace: nginx-ingress
roleRef:
  kind: ClusterRole
  name: nginx-ingress-manager
  
  
  