apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-locking-jupyterhub-client-provisioner
  namespace: jupyterhub
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get","create","update","patch"]